version: "3.1"
services:
  db:
    container_name: example-db
    image: postgres:13.4
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=q1w2e3r4
    volumes:
      - db_volume:/var/lib/postgresql/data
  redis:
    container_name: example-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - redis_network
  redis-commander:
    container_name: example-redis-commander
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - redis_network

volumes:
  db_volume:
networks:
  redis_network: